service: serverless-movie-api

frameworkVersion: "3"

plugins:
  - serverless-plugin-resource-tagging
  - serverless-ssm-fetch
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8

  stage: ${env:environment}
  region: ${env:region}

  stackTags:
    ServerlessFramework: "True"
    Timestamp: ${env:timestamp}
    Environment: ${env:environment}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: arn:aws:lambda:*:*:function:*

custom:
  serverlessSsmFetch:
    bucket_id: /${env:environment}/${env:ssm_path}
  pythonRequirements:
    dockerizePip: non-linux

functions:
  source-file-download:
    handler: handler.handler
    events:
      # every day at 11:15 AM
      - schedule: cron(15 11 ? * * *)
    environment:
      KAGGLE_USERNAME: ${env:KAGGLE_USERNAME}
      KAGGLE_KEY: ${env:KAGGLE_KEY}
