service: serverless-movie-api

frameworkVersion: "3"

plugins:
  - serverless-plugin-resource-tagging
  - serverless-ssm-fetch

provider:
  name: aws
  runtime: python3.8

  stage: ${env:environment}
  region: ${env:region}

  stackTags:
    ServerlessFramework: "True"
    Timestamp: ${env:timestamp}
    Environment: ${env:environment}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: arn:aws:lambda:*:*:function:*
    - Effect: Allow
      Action:
        - s3:PutItem
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${custom:serverlessSsmFetch.bucket_id}
    - Effect: Allow
      Action:
        - s3:PutItem
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${custom:serverlessSsmFetch.bucket_id}/*

custom:
  serverlessSsmFetch:
    bucket_id: /${env:environment}/${env:ssm_path}

functions:
  source-file-download:
    handler: handler.handler
    events:
      # every day at 11:15 AM
      - schedule: cron(15 11 ? * * *)
    environment:
      KAGGLE_USERNAME: ${env:KAGGLE_USERNAME}
      KAGGLE_KEY: ${env:KAGGLE_KEY}
      bucket_id: ${custom:serverlessSsmFetch.bucket_id}
