service: serverless-movie-api

frameworkVersion: "3"

plugins:
  - serverless-plugin-resource-tagging

provider:
  name: aws
  runtime: python3.8

  stage: ${env:environment}
  region: ${env:region}

  stackTags:
    ServerlessFramework: "True"
    Timestamp: ${env:timestamp}
    Environment: ${env:environment}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: arn:aws:lambda:*:*:function:*
    - Effect: Allow
      Action:
        - s3:PutItem
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.movieSourceFileBucket}
    - Effect: Allow
      Action:
        - s3:PutItem
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.movieSourceFileBucket}/*

custom:
  bucket_name: ${ssm:${env:ssm_path}}
  movieSourceFileBucket: ${env:environment}/${env:ssm_path}

functions:
  source-file-download:
    handler: handler.handler
    events:
      # every day at 11:15 AM
      - schedule: cron(15 11 ? * * *)
    environment:
      KAGGLE_USERNAME: ${env:KAGGLE_USERNAME}
      KAGGLE_KEY: ${env:KAGGLE_KEY}
      source_bucket: ${self:custom.movieSourceFileBucket}
